### PR TITLE
Feat ear report

### PR DESCRIPTION
**Pull request by lkorczowski**
- [x] clean Inter_subject_analysis (bruxism)
    * make it work on my computer
    * export as much as possible cells in module for replicability for ear activation

### CODE REVIEW

**Comment by lkorczowski** [comment]
Issue because inter-subject NB (bruxism) doesn't handle missing channel, see #45

**Comment by RobinGuillard** [comment]
Hello !

Just to inform you that after a meticulous analysis, it has been found that the best suited processing steps to spot middle ear events on Airflow channel is by making a 2 step approach : first make a classification with parameters : epochs =1s, abs_thr = 0, rel_thr = 3,5, n_adaptative = 0 (global baseline) and then make a classification with parameters : epochs =1s, abs_thr = 0, rel_thr = 3, n_adaptative = 60 (60s baseline). Join the results so that epochs are not flagged 2 times...
BUT : it has been noticed that for 6 of the recordings (the followings: 1GB19, 1MF19, SCHM_nuit_3, Robin_mema_2, Sophie_mema, Tom_mema), there were periods where the sensor measured abnormal rythmical activity, and thus ONLY the adaptative baseline step should be used (epochs =1s, abs_thr = 0, rel_thr = 3, n_adaptative = 60). It has been checked on all these recordings that it works better :)

**Comment by RobinGuillard** [comment]
Moreover, it has been noticed that :
- recording jose_mema is not suited for analysis as there was a sensor disconnection after 1/4 of the recording
- There is a possibility that there is on 1MF19's recording a  disconnection as well, but only for the last 1/4 of the recording but it is not sure as there is still signs of the baseline

- on 3 recordings, the sensor used was slightly different (1DA15, robin_mema_nuit_1, robin_mema_nuit_2). It appears that the recording robin_mema_nuit_1 is not good for analysis (weird activity), and no prefiltering seems to be needed for the other 2 recordings (no significative influence of the filtering)

**Comment by lkorczowski** [comment]
> Hello !
> 
> Just to inform you that after a meticulous analysis, it has been found that the best suited processing steps to spot middle ear events on Airflow channel is by making a 2 step approach : first make a classification with parameters : epochs =1s, abs_thr = 0, rel_thr = 3,5, n_adaptative = 0 (global baseline) and then make a classification with parameters : epochs =1s, abs_thr = 0, rel_thr = 3, n_adaptative = 60 (60s baseline). Join the results so that epochs are not flagged 2 times...

Great. How would you like to merge the two classifiers ? Logical OR, logical AND ?

> BUT : it has been noticed that for 6 of the recordings (the followings: 1GB19, 1MF19, SCHM_nuit_3, Robin_mema_2, Sophie_mema, Tom_mema), there were periods where the sensor measured abnormal rythmical activity, and thus ONLY the adaptative baseline step should be used (epochs =1s, abs_thr = 0, rel_thr = 3, n_adaptative = 60). It has been checked on all these recordings that it works better :)

Unfortunately, we can't have different classification pipeline for different people. While it may works when you tag by hand, the analysis just won't be valid if we apply different criteria to different subject. Therefore, we should pick one pipeline or both for all subject.

**Comment by lkorczowski** [comment]
> Moreover, it has been noticed that :
> 
>     * recording jose_mema is not suited for analysis as there was a sensor disconnection after 1/4 of the recording
> 
>     * There is a possibility that there is on 1MF19's recording a  disconnection as well, but only for the last 1/4 of the recording but it is not sure as there is still signs of the baseline
> 
>     * on 3 recordings, the sensor used was slightly different (1DA15, robin_mema_nuit_1, robin_mema_nuit_2). It appears that the recording robin_mema_nuit_1 is not good for analysis (weird activity), and no prefiltering seems to be needed for the other 2 recordings (no significative influence of the filtering)

Please provide a .pk file that we can load and put in in Resources (or append a new column to an existing pk).

**Comment by RobinGuillard** [comment]
It has been found that the technique that works the best for all recording is an adaptative baseline foward-backward. The parameters advised are:
epochs : 1s, abs_THR 0, rel_THR 3.5, n_adaptive=60.

The process steps are to make one pass foward, one pass backwards and to make a logical OR out the results to save the union of the events.

Here is a suggestion for the backward loop coding:
`epochs = epochs[ : :-1]
    
     # compute the sum of power over electrodes and samples in each window
    pipeline = AmplitudeThresholding(abs_threshold=0., rel_threshold=3.5, n_adaptive=60)
    X        = rms(epochs) # take only valid labels
    labels   = pipeline.fit_predict(X)
    
    labels = labels[ : :-1]`

Note that it is important to reverse the label output at the end to "find back" the good order for the labels.

**Comment by RobinGuillard** [comment]
> 
> 
> > Moreover, it has been noticed that :
> > ```
> > * recording jose_mema is not suited for analysis as there was a sensor disconnection after 1/4 of the recording
> > 
> > * There is a possibility that there is on 1MF19's recording a  disconnection as well, but only for the last 1/4 of the recording but it is not sure as there is still signs of the baseline
> > 
> > * on 3 recordings, the sensor used was slightly different (1DA15, robin_mema_nuit_1, robin_mema_nuit_2). It appears that the recording robin_mema_nuit_1 is not good for analysis (weird activity), and no prefiltering seems to be needed for the other 2 recordings (no significative influence of the filtering)
> > ```
> 
> Please provide a .pk file that we can load and put in in Resources (or append a new column to an existing pk).

It appears to me in the end that jose_mema, robin_mema_nuit_1, robin_mema_nuit_2, and 1DA15 should be simply removed of the analysis for now.

**Pull request merged**
