### PR TITLE
Refactor sfreq to 250

### LINKED ISSUE #62: Bad pratice: hardcoded sfreq in CreateRaw
So usually "simple" task of refactoring sfreq dig an interesting bad practice (see #61 ):
- hardcoding parameters ^^

We should end this :)

### LINKED ISSUE #63: scoring: TypeError: '<' not supported between instances of 'int' and 'dict'
Fix needed to recompute all Bruxism results after #61 

observed in Bruxism_Inter_subject (no problem in Middle_ear_Inter_subject)

Track of the problem: 
* main diff is the use of  `generate_bruxism_report`
* issue is not recent as I capture it in both master and new branchs
* somewhere in `burst_list[i].beg - current_epi.end` returns a `dict` instead of a float

```
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-9791581e0776> in <module>
     41             print("report...", end=" ");tmp = time()
     42             if np.sum(valid_labels)>0 :
---> 43                 results[filename] = reporting(epochs, valid_labels, THR_classif, n_adaptive, log)
     44                 print(f"DONE ({time()-tmp:.2f}s)")
     45             else:

~/git/Tinnitus-n-Sleep/notebooks/../tinnsleep/create_reports.py in reporting(epochs, valid_labels, THR_classif, time_interval, delim, n_adaptive, log, generate_report)
    132             labels = np.any(np.c_[labels, labels_b], axis=-1)
    133 
--> 134         report = generate_report(labels, time_interval, delim)
    135         labels = fuse_with_classif_result(np.invert(valid_labels),
    136                                           labels)  # add the missing labels removed with artefacts

~/git/Tinnitus-n-Sleep/notebooks/../tinnsleep/scoring.py in generate_bruxism_report(classif, time_interval, delim)
    234     report["Total number of burst"] = nb_burst
    235     report["Number of bursts per hour"] = nb_burst * 3600 / recording_duration
--> 236     li_episodes = burst_to_episode(li_burst, delim)
    237     nb_episodes = len(li_episodes)
    238     report["Total number of episodes"] = nb_episodes

~/git/Tinnitus-n-Sleep/notebooks/../tinnsleep/scoring.py in burst_to_episode(burst_list, delim, min_burst_joining)
    101     # Loop that reunites bursts within the same episode
    102     while (i < leny):
--> 103         if burst_list[i].beg - current_epi.end < delim:
    104             # The burst can be added to the current episode
    105             current_epi.add_a_burst(burst_list[i])

TypeError: '<' not supported between instances of 'int' and 'dict'
```

### PR DESCRIPTION
**Pull request by lkorczowski**
- [x] refactor sfreq to 250 everywhere
- [x] correct pytest that used hardcoded sfreq
- [x] refactor all function with hardcoded sfreq and now being a mandatory parameter. 
- [x] compare results of NB with master.
closes #62 
closes #63

### CODE REVIEW

**Comment by lkorczowski** [comment]
inter-subject MEMA works
but 
inter-subject bruxism show this error #63

**Comment by lkorczowski** [comment]
ready to be merge when reviewed @RobinGuillard

**Comment by lkorczowski** [comment]
currently running the MEMA inter, will push tonight.

can't do for bruxism because #63

**Comment by RobinGuillard** [comment]
Proposed a fix to #63, please try and see if it works.

**Pull request merged**
